language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
addons:
  chrome: stable

branches:
  only:
    - master
before_script:
  - npm install -g --silent @angular/cli
  - npm install -g karma-cli
script:
  - npm run test
  - npm run buildgp
