sudo: required
dist: trusty
language: python

python: 2.7

addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng test
